WebServicos/Models/Servico.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using static WebServicos.Models.Enum;

namespace WebServicos.Models
{
    public class Servico
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [Display(Name = "Descrição")]
        public string Descricao { get; set; }
        [Required]
        [DataType(DataType.Date)]
        public DateTime Data { get; set; }
        [Required]
        [DataType(DataType.Currency)]
        public decimal Valor { get; set; }
        [Required]
        [Display(Name = "Tipo Serviço")]
        public TipoServico TipoServico { get; set; }
        [Display(Name = "Cliente")]
        [ForeignKey("Cliente")]
        public int Cliente_ID { get; set; }
        public Cliente Cliente { get; set; }
        [Display(Name = "Fornecedor")]
        [ForeignKey("Fornecedor")]
        public int Fornecedor_ID { get; set; }
        public Fornecedor Fornecedor { get; set; }
    }
}

WebServicos/Controllers/ServicoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using WebServicos.Domain;
using WebServicos.Repository;

namespace WebServicos.Controllers
{
    [Authorize]
    public class ServicoController : Controller
    {
        private readonly ServicoRepository _servicoRepository = new ServicoRepository();

        // GET: Servico
        public ActionResult Index()
        {
            return View(_servicoRepository.List());
        }

        // GET: Servico/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Servico servico = _servicoRepository.Get((int)id);
            if (servico == null)
            {
                return HttpNotFound();
            }
            return View(servico);
        }

        // GET: Servico/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Servico/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Descricao,Data,Valor,TipoServico,Cliente_ID,Fornecedor_ID")] Servico servico)
        {
            FornecedorRepository fornecedorRepository = new FornecedorRepository();
            if (!string.IsNullOrEmpty(User?.Identity?.Name))
                servico.Fornecedor_ID = fornecedorRepository.List().FirstOrDefault(x => x.Email == User.Identity.Name).Id;
            if (servico.Fornecedor_ID == 0)
                ModelState.AddModelError(string.Empty, TempData["Não foi possível identificar o fornecedor."].ToString());
            if (ModelState.IsValid && servico.Fornecedor_ID > 0)
            {
                _servicoRepository.Add(servico);
                return RedirectToAction("Index", servico.Id);
            }

            return View(servico);
        }

        // GET: Servico/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Servico servico = _servicoRepository.Get((int)id);
            if (servico == null)
            {
                return HttpNotFound();
            }
            return View(servico);
        }

        // POST: Servico/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Descricao,Data,Valor,TipoServico,Cliente_ID,Fornecedor_ID")] Servico servico)
        {
            if (ModelState.IsValid)
            {
                _servicoRepository.Update(servico);
                return RedirectToAction("Index");
            }
            return View(servico);
        }

        // GET: Servico/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Servico servico = _servicoRepository.Get((int)id);
            if (servico == null)
            {
                return HttpNotFound();
            }
            return View(servico);
        }

        // POST: Servico/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            _servicoRepository.Delete(id);
            return RedirectToAction("Index");
        }

        // GET: Report
        [HttpGet]
        public ActionResult Report()
        {
            return View("Report");
        }

        // GET: ReportResult
        [HttpGet]
        public ActionResult ReportResult([Bind(Include = "Cliente, Estado, Cidade, Bairro, TipoServico, ValMin, ValMax")] Util.Filter filter, int? page)
        {
            List<Servico> servicos = _servicoRepository.List();
            if (!string.IsNullOrEmpty(filter?.Bairro))
                servicos = servicos.Where(x => x.Cliente.Bairro.Equals(filter.Bairro)).ToList();
            if (!string.IsNullOrEmpty(filter?.Cidade))
                servicos = servicos.Where(x => x.Cliente.Cidade.Equals(filter.Cidade)).ToList();
            if (!string.IsNullOrEmpty(filter?.Estado))
                servicos = servicos.Where(x => x.Cliente.Estado.Equals(filter.Estado)).ToList();
            if (filter != null && filter.Cliente > 0)
                servicos = servicos.Where(x => x.Cliente_ID.Equals(filter.Cliente)).ToList();
            if (filter != null && filter.TipoServico != 0)
                servicos = servicos.Where(x => x.TipoServico.Equals(filter.TipoServico)).ToList();
            if (filter != null && filter.ValMax > 0)
                servicos = servicos.Where(x => x.Valor <= filter.ValMax).ToList();
            if (filter != null && filter.ValMin > 0)
                servicos = servicos.Where(x => x.Valor >= filter.ValMin).ToList();

            int pageSize = 10;
            int currentPage = (page ?? 0);
            ViewBag.Pages = Math.Ceiling((decimal)servicos.Count() / pageSize);
            ViewBag.CurrentPage = currentPage;
            return View("_ReportResult", servicos.Skip(currentPage * pageSize).Take(pageSize));
        }

        // GET: Servico
        [AllowAnonymous]
        public ActionResult Stats()
        {
            return View("Stats", _servicoRepository.List());
        }

    }
}

WebServicos/Views/Servico/Create.cshtml
@model WebServicos.Domain.Servico

@{
    ViewBag.Title = "Adicionar";
}

<h2>Adicionar</h2>
@{
    var clientes = new WebServicos.Domain.ServicosContext().Cliente.Select(x => new SelectListItem { Value = x.Id.ToString(), Text = x.Nome }).ToList();
    clientes.Add(new SelectListItem { Value = "0", Text = "Selecione", Selected = true });
    clientes = clientes.OrderBy(x => x.Value).ToList();
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Servico</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Data, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Data, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Data, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Valor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Valor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Valor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TipoServico, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.TipoServico, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TipoServico, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cliente_ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Cliente_ID, clientes, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Cliente_ID, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Adicionar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebServicos/Views/Servico/Delete.cshtml
@model WebServicos.Domain.Servico

@{
    ViewBag.Title = "Deletar";
}

<h2>Deletar</h2>

<h3>Tem certeza que deseja deletar este item?</h3>
<div>
    <h4>Servico</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Data)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Data)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Valor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Valor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoServico)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoServico)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cliente_ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cliente_ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fornecedor_ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fornecedor_ID)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Voltar", "Index")
        </div>
    }
</div>

WebServicos/Views/Servico/Details.cshtml
@model WebServicos.Domain.Servico

@{
    ViewBag.Title = "Detalhes";
}

<h2>Detalhes</h2>

<div>
    <h4>Servico</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Data)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Data)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Valor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Valor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoServico)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoServico)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cliente_ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cliente_ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fornecedor_ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fornecedor_ID)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Voltar", "Index")
</p>

WebServicos/Views/Servico/Edit.cshtml
@model WebServicos.Domain.Servico

@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>
@{
    var clientes = new WebServicos.Domain.ServicosContext().Cliente.Select(x => new SelectListItem { Value = x.Id.ToString(), Text = x.Nome }).ToList();
    clientes.Add(new SelectListItem { Value = "0", Text = "Selecione"});
    clientes.FirstOrDefault(x => x.Value == Model.Cliente_ID.ToString()).Selected = true;
    clientes = clientes.OrderBy(x => x.Value).ToList();
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Servico</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Data, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Data, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Data, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Valor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Valor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Valor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TipoServico, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.TipoServico, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TipoServico, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cliente_ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Cliente_ID, clientes, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Cliente_ID, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Adicionar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebServicos/Views/Servico/Index.cshtml
@model IEnumerable<WebServicos.Domain.Servico>

@{
    ViewBag.Title = "Serviços";
}
<h2>Serviços</h2>
<p>
    @Html.ActionLink("Adicionar", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Descricao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Data)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Valor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TipoServico)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cliente)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fornecedor)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Descricao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Data)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Valor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TipoServico)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cliente.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fornecedor.Nome)
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Detalhes", "Details", new { id = item.Id }) |
                @Html.ActionLink("Deletar", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>

WebServicos/Views/Servico/Report.cshtml
@model WebServicos.Util.Filter
@using Newtonsoft.Json

<script>
    var reportUrl = '@Url.Action("ReportResult", "Servico")';
    function report(page) {
        var settings = {
            "async": true,
            "crossDomain": true,
            "url": "/Servico/ReportResult?Cliente=" + $("#Cliente").val() + "&Estado=" + $("#Estado").val()
                + "&Cidade=" + $("#Cidade").val() + "&Bairro=" + $("#Bairro").val() + "&TipoServico=" + $("#TipoServico     ").val()
                + "&ValMin=" + $("#ValMin").val() + "&ValMax=" + $("#ValMax").val() + "&Page=" + page,
            "method": "GET"
        }

        $.ajax(settings).done(function (response) {
            $('#reportResult').html(response);
        });
    };
    window.onload = function () {
        report();
    };

</script>
<h2 class="mt-4 mb-4">Relatório de Serviços</h2>
@{
    var clientes = new WebServicos.Domain.ServicosContext().Cliente.Select(x => new SelectListItem { Value = x.Id.ToString(), Text = x.Nome }).ToList();
    clientes.Add(new SelectListItem { Value = "0", Text = "", Selected = true });
    clientes = clientes.OrderBy(x => x.Value).ToList();
}
<div class="card">
    <a class="card-header btn btn-default text-left" data-toggle="collapse" href="#collapsefilter" role="button" aria-expanded="false" aria-controls="collapseExample">Filtros</a>
    <div class="card-body collapse" id="collapsefilter">
        <div id="form" class=" row">
            <div class="form-group col-3">
                @Html.LabelFor(model => model.Cliente, htmlAttributes: new { @class = "control-label" })
                @Html.DropDownListFor(model => model.Cliente, clientes, htmlAttributes: new { @class = "form-control" })
            </div>
            <div class="form-group col-3">
                @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Estado, new { htmlAttributes = new { @class = "form-control" } })
            </div>
            <div class="form-group col-3">
                @Html.LabelFor(model => model.Cidade, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Cidade, new { htmlAttributes = new { @class = "form-control" } })
            </div>
            <div class="form-group col-3">
                @Html.LabelFor(model => model.Bairro, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Bairro, new { htmlAttributes = new { @class = "form-control" } })
            </div>
            <div class="form-group col-3">
                @Html.LabelFor(model => model.TipoServico, htmlAttributes: new { @class = "control-label" })
                @Html.EnumDropDownListFor(model => model.TipoServico, htmlAttributes: new { @class = "form-control" })
            </div>
            <div class="form-group col-3">
                @Html.LabelFor(model => model.ValMin, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.ValMin, new { htmlAttributes = new { @class = "form-control" } })
            </div>
            <div class="form-group col-3">
                @Html.LabelFor(model => model.ValMax, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.ValMax, new { htmlAttributes = new { @class = "form-control" } })
            </div>
            <div class="form-group col-3">
                <div class="mt-4 ml-5">
                    <input type="button" value="Filtrar" class="btn btn-default mx-auto" onclick="report()" />
                </div>
            </div>
        </div>
    </div>
</div>
<div id="reportResult" class="mt-4">
    @Html.Partial("_ReportResult")
</div>

WebServicos/Views/Servico/Stats.cshtml
@model IEnumerable<WebServicos.Domain.Servico>

@{
    ViewBag.Title = "Estatísticas";
}
<h2 class="mt-4">Estatísticas</h2>
@Html.Partial("_StatsTopCostumers", Model)
<hr />
@Html.Partial("_StatsProviders", Model)
<hr />
@Html.Partial("_StatsProvidersTypeServices", Model)
<hr />

WebServicos/Views/Servico/_ReportResult.cshtml
@model IEnumerable<WebServicos.Domain.Servico>
@using WebServicos.Domain
@{
    Layout = null;
}

@if (Model != null)
{
    <nav aria-label="Page navigation example" id="pagination">
        <ul class="pagination justify-content-center">
            <li class="page-item @(ViewBag.CurrentPage == 0 ? "disabled" : "")">
                <a class="page-link" href="#pagination" tabindex="-1" onclick="report(@(ViewBag.CurrentPage - 1))">Anterior</a>
            </li>
            @for (int i = 0; i < ViewBag.Pages; i++)
            {
                <li class="page-item @(ViewBag.CurrentPage == i ? "disabled" : "")"><a class="page-link" onclick="report(@i)" href="#pagination">@(i+1)</a></li>
            }
            <li class="page-item @(ViewBag.CurrentPage + 1 == ViewBag.Pages ? "disabled" : "")">
                <a class="page-link" href="#pagination" onclick="report(@(ViewBag.CurrentPage + 1))">Próximo</a>
            </li>
        </ul>
    </nav>
    <table class="table table-striped">
        <tr>
            <th scope="col">
                @Html.DisplayNameFor(model => model.Cliente.Nome)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.Cliente.Bairro)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.Cliente.Cidade)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.Cliente.Estado)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.TipoServico)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.Valor)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.Data)
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <th scope="row">
                    @Html.DisplayFor(modelItem => item.Cliente.Nome)
                </th>
                <td>
                    @Html.DisplayFor(modelItem => item.Cliente.Bairro)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cliente.Cidade)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cliente.Estado)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TipoServico)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Valor)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Data)
                </td>
            </tr>
        }
    </table>
}

WebServicos/Views/Servico/_StatsProviders.cshtml
@model IEnumerable<WebServicos.Domain.Servico>
@using System.Globalization
@{
    Layout = null;
    var fornecedores = new WebServicos.Domain.ServicosContext().Fornecedor.ToList();
}
<div class="card mt-4 mb-4">
    <h3 class="card-header btn text-left bg-dark text-white" data-toggle="collapse" href="#collapseProviders" role="button" aria-expanded="true" aria-controls="collapseProviders">Fornecedores sem compra</h3>
    <div class="card-body collapse show px-1" id="collapseProviders">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">
                        Mês
                    </th>
                    <th scope="col">
                        Fornecedor
                    </th>
                </tr>
            </thead>
            @for (int i = 1; i <= DateTime.Now.Month; i++)
            {
                bool firstMonth = true;
                var fornecedoresMes = fornecedores.Where(s => !Model.Where(y => y.Data.Month == i && y.Data.Year == DateTime.Now.Year).Any(x => x.Fornecedor_ID == s.Id));
                foreach (var item in fornecedoresMes)
                {
                    <tr>
                        @if (firstMonth)
                        {
                            firstMonth = false;
                            CultureInfo cinfo = CultureInfo.CreateSpecificCulture("pt-BR");
                            <td rowspan="@(fornecedoresMes.Count())" class="align-middle"> @cinfo.DateTimeFormat.GetMonthName(i) </td>
                        }
                        <td> @item.Nome</td>
                    </tr>
                }

            }
        </table>
    </div>
</div>

WebServicos/Views/Servico/_StatsProvidersTypeServices.cshtml
@model IEnumerable<WebServicos.Domain.Servico>
@{
    Layout = null;
}
<div class="card mt-4 mb-4">
    <h3 class="card-header btn text-left bg-dark text-white" data-toggle="collapse" href="#collapseProvidersTypeServices" role="button" aria-expanded="true" aria-controls="collapseProvidersTypeServices">Média por Fornecedor e Tipo de Serviço</h3>
    <div class="card-body collapse show px-1" id="collapseProvidersTypeServices">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">
                        Fornecedor
                    </th>
                    <th scope="col">
                        Tipo Serviço
                    </th>
                    <th scope="col">
                        Valor
                    </th>
                </tr>
            </thead>
            @{
                int fornecedor = 0;
                var group = Model.GroupBy(x => new { x.Fornecedor_ID, x.TipoServico }).Select(y =>
                new WebServicos.Domain.Servico
                {
                    Fornecedor = y.First().Fornecedor,
                    Fornecedor_ID = y.First().Fornecedor_ID,
                    TipoServico = y.First().TipoServico,
                    Valor = y.Average(s => s.Valor)
                }
                ).OrderBy(x => x.Fornecedor_ID);
            }
            @foreach (var item in group)
            {
                <tr>
                    @if (item.Fornecedor_ID != fornecedor)
                    {
                        fornecedor = item.Fornecedor_ID;
                        <td rowspan="@group.Where(x => x.Fornecedor_ID == item.Fornecedor_ID).Count()" class="align-middle">@item.Fornecedor.Nome</td>
                    }
                    <td>@item.TipoServico</td>
                    <td>@item.Valor.ToString("C")</td>
                </tr>
            }
        </table>
    </div>
</div>

WebServicos/Views/Servico/_StatsTopCostumers.cshtml
@model IEnumerable<WebServicos.Domain.Servico>
@using System.Globalization
@using WebServicos.Domain
@{
    Layout = null;
}
<div class="card mt-4 mb-4">
    <h3 class="card-header btn text-left bg-dark text-white" data-toggle="collapse" href="#collapseTopCostumers" role="button" aria-expanded="true" aria-controls="collapseTopCostumers">Top Clientes</h3>
    <div class="card-body collapse show px-1" id="collapseTopCostumers">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">
                        Mês
                    </th>
                    <th scope="col">
                        Cliente
                    </th>
                    <th scope="col">
                        Valor total
                    </th>
                </tr>
            </thead>
            @for (int i = 1; i <= DateTime.Now.Month; i++)
            {
                bool firstMonth = true;
                var topVendedores = Model.Where(x => x.Data.Month == i && x.Data.Year == DateTime.Now.Year).GroupBy(x => x.Cliente_ID).Select(y =>
                new Servico { Cliente = y.First().Cliente, Data = y.First().Data, Valor = y.Sum(s => s.Valor) }
                ).Take(3).OrderByDescending(x => x.Valor).ToList();
                foreach (var item in topVendedores)
                {
                    <tr>
                        @if (firstMonth)
                        {
                            firstMonth = false;
                            <td rowspan="@topVendedores.Count())" class="align-middle">@Model.Where(x => x.Data.Month == i && x.Data.Year == DateTime.Now.Year).FirstOrDefault().Data.ToString("MMMM")</td>
                        }
                        <td>@item.Cliente.Nome</td>
                        <td>@item.Valor.ToString("C")</td>
                    </tr>
                }
                if (!topVendedores.Any())
                {
                    CultureInfo cinfo = CultureInfo.CreateSpecificCulture("pt-BR");
                    <tr>
                        <td>@cinfo.DateTimeFormat.GetMonthName(i)</td>
                        <td>SEM CLIENTES</td>
                        <td></td>
                    </tr>
                }
            }
        </table>
    </div>
</div>